// flow-typed signature: 98475fdd322f8ea154f2a6eebb042745
// flow-typed version: <<STUB>>/harvest_v^0.1.5/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'harvest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'harvest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'harvest/lib/account' {
  declare module.exports: any;
}

declare module 'harvest/lib/client-contacts' {
  declare module.exports: any;
}

declare module 'harvest/lib/clients' {
  declare module.exports: any;
}

declare module 'harvest/lib/expense-categories' {
  declare module.exports: any;
}

declare module 'harvest/lib/expenses' {
  declare module.exports: any;
}

declare module 'harvest/lib/invoice-categories' {
  declare module.exports: any;
}

declare module 'harvest/lib/invoice-messages' {
  declare module.exports: any;
}

declare module 'harvest/lib/invoice-payments' {
  declare module.exports: any;
}

declare module 'harvest/lib/invoices' {
  declare module.exports: any;
}

declare module 'harvest/lib/people' {
  declare module.exports: any;
}

declare module 'harvest/lib/projects' {
  declare module.exports: any;
}

declare module 'harvest/lib/reports' {
  declare module.exports: any;
}

declare module 'harvest/lib/task-assignment' {
  declare module.exports: any;
}

declare module 'harvest/lib/tasks' {
  declare module.exports: any;
}

declare module 'harvest/lib/time-tracking' {
  declare module.exports: any;
}

declare module 'harvest/lib/user-assignment' {
  declare module.exports: any;
}

declare module 'harvest/mixin' {
  declare module.exports: any;
}

declare module 'harvest/test/account-api-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/client-contacts-api-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/clients-api-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/expense-tracking-api-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/expenses-api-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/harvest-client-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/invoice-categories-api-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/invoice-messages-api-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/invoice-payments-api-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/invoices-api-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/mixin-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/people-api-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/projects-api-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/reports-api-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/task-assignment-api-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/tasks-api-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/time-tracking-api-tests' {
  declare module.exports: any;
}

declare module 'harvest/test/user-assignment-api-tests' {
  declare module.exports: any;
}

declare module 'harvest/throttle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'harvest/index' {
  declare module.exports: $Exports<'harvest'>;
}
declare module 'harvest/index.js' {
  declare module.exports: $Exports<'harvest'>;
}
declare module 'harvest/lib/account.js' {
  declare module.exports: $Exports<'harvest/lib/account'>;
}
declare module 'harvest/lib/client-contacts.js' {
  declare module.exports: $Exports<'harvest/lib/client-contacts'>;
}
declare module 'harvest/lib/clients.js' {
  declare module.exports: $Exports<'harvest/lib/clients'>;
}
declare module 'harvest/lib/expense-categories.js' {
  declare module.exports: $Exports<'harvest/lib/expense-categories'>;
}
declare module 'harvest/lib/expenses.js' {
  declare module.exports: $Exports<'harvest/lib/expenses'>;
}
declare module 'harvest/lib/invoice-categories.js' {
  declare module.exports: $Exports<'harvest/lib/invoice-categories'>;
}
declare module 'harvest/lib/invoice-messages.js' {
  declare module.exports: $Exports<'harvest/lib/invoice-messages'>;
}
declare module 'harvest/lib/invoice-payments.js' {
  declare module.exports: $Exports<'harvest/lib/invoice-payments'>;
}
declare module 'harvest/lib/invoices.js' {
  declare module.exports: $Exports<'harvest/lib/invoices'>;
}
declare module 'harvest/lib/people.js' {
  declare module.exports: $Exports<'harvest/lib/people'>;
}
declare module 'harvest/lib/projects.js' {
  declare module.exports: $Exports<'harvest/lib/projects'>;
}
declare module 'harvest/lib/reports.js' {
  declare module.exports: $Exports<'harvest/lib/reports'>;
}
declare module 'harvest/lib/task-assignment.js' {
  declare module.exports: $Exports<'harvest/lib/task-assignment'>;
}
declare module 'harvest/lib/tasks.js' {
  declare module.exports: $Exports<'harvest/lib/tasks'>;
}
declare module 'harvest/lib/time-tracking.js' {
  declare module.exports: $Exports<'harvest/lib/time-tracking'>;
}
declare module 'harvest/lib/user-assignment.js' {
  declare module.exports: $Exports<'harvest/lib/user-assignment'>;
}
declare module 'harvest/mixin.js' {
  declare module.exports: $Exports<'harvest/mixin'>;
}
declare module 'harvest/test/account-api-tests.js' {
  declare module.exports: $Exports<'harvest/test/account-api-tests'>;
}
declare module 'harvest/test/client-contacts-api-tests.js' {
  declare module.exports: $Exports<'harvest/test/client-contacts-api-tests'>;
}
declare module 'harvest/test/clients-api-tests.js' {
  declare module.exports: $Exports<'harvest/test/clients-api-tests'>;
}
declare module 'harvest/test/expense-tracking-api-tests.js' {
  declare module.exports: $Exports<'harvest/test/expense-tracking-api-tests'>;
}
declare module 'harvest/test/expenses-api-tests.js' {
  declare module.exports: $Exports<'harvest/test/expenses-api-tests'>;
}
declare module 'harvest/test/harvest-client-tests.js' {
  declare module.exports: $Exports<'harvest/test/harvest-client-tests'>;
}
declare module 'harvest/test/invoice-categories-api-tests.js' {
  declare module.exports: $Exports<'harvest/test/invoice-categories-api-tests'>;
}
declare module 'harvest/test/invoice-messages-api-tests.js' {
  declare module.exports: $Exports<'harvest/test/invoice-messages-api-tests'>;
}
declare module 'harvest/test/invoice-payments-api-tests.js' {
  declare module.exports: $Exports<'harvest/test/invoice-payments-api-tests'>;
}
declare module 'harvest/test/invoices-api-tests.js' {
  declare module.exports: $Exports<'harvest/test/invoices-api-tests'>;
}
declare module 'harvest/test/mixin-tests.js' {
  declare module.exports: $Exports<'harvest/test/mixin-tests'>;
}
declare module 'harvest/test/people-api-tests.js' {
  declare module.exports: $Exports<'harvest/test/people-api-tests'>;
}
declare module 'harvest/test/projects-api-tests.js' {
  declare module.exports: $Exports<'harvest/test/projects-api-tests'>;
}
declare module 'harvest/test/reports-api-tests.js' {
  declare module.exports: $Exports<'harvest/test/reports-api-tests'>;
}
declare module 'harvest/test/task-assignment-api-tests.js' {
  declare module.exports: $Exports<'harvest/test/task-assignment-api-tests'>;
}
declare module 'harvest/test/tasks-api-tests.js' {
  declare module.exports: $Exports<'harvest/test/tasks-api-tests'>;
}
declare module 'harvest/test/time-tracking-api-tests.js' {
  declare module.exports: $Exports<'harvest/test/time-tracking-api-tests'>;
}
declare module 'harvest/test/user-assignment-api-tests.js' {
  declare module.exports: $Exports<'harvest/test/user-assignment-api-tests'>;
}
declare module 'harvest/throttle.js' {
  declare module.exports: $Exports<'harvest/throttle'>;
}
