// flow-typed signature: 0057325d8a2183792690c40a6c35bde3
// flow-typed version: <<STUB>>/mongodb-runner_v3.4.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongodb-runner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongodb-runner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongodb-runner/bin/mongodb-runner-worker' {
  declare module.exports: any;
}

declare module 'mongodb-runner/bin/mongodb-runner' {
  declare module.exports: any;
}

declare module 'mongodb-runner/lib/index' {
  declare module.exports: any;
}

declare module 'mongodb-runner/lib/worker' {
  declare module.exports: any;
}

declare module 'mongodb-runner/mocha/after' {
  declare module.exports: any;
}

declare module 'mongodb-runner/mocha/before' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongodb-runner/bin/mongodb-runner-worker.js' {
  declare module.exports: $Exports<'mongodb-runner/bin/mongodb-runner-worker'>;
}
declare module 'mongodb-runner/bin/mongodb-runner.js' {
  declare module.exports: $Exports<'mongodb-runner/bin/mongodb-runner'>;
}
declare module 'mongodb-runner/index' {
  declare module.exports: $Exports<'mongodb-runner'>;
}
declare module 'mongodb-runner/index.js' {
  declare module.exports: $Exports<'mongodb-runner'>;
}
declare module 'mongodb-runner/lib/index.js' {
  declare module.exports: $Exports<'mongodb-runner/lib/index'>;
}
declare module 'mongodb-runner/lib/worker.js' {
  declare module.exports: $Exports<'mongodb-runner/lib/worker'>;
}
declare module 'mongodb-runner/mocha/after.js' {
  declare module.exports: $Exports<'mongodb-runner/mocha/after'>;
}
declare module 'mongodb-runner/mocha/before.js' {
  declare module.exports: $Exports<'mongodb-runner/mocha/before'>;
}
