// flow-typed signature: 625b6139b4ce37d9c37583cd8c71efea
// flow-typed version: <<STUB>>/parse-server_v2.3.7/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parse-server/lib/AccountLockout' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/AdapterLoader' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Analytics/AnalyticsAdapter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/AuthAdapter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/facebook' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/github' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/google' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/index' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/instagram' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/janraincapture' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/janrainengage' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/linkedin' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/meetup' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/OAuth1Client' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/qq' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/spotify' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/twitter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/vkontakte' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/wechat' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Auth/weibo' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Cache/CacheAdapter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Cache/InMemoryCache' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Cache/InMemoryCacheAdapter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Cache/NullCacheAdapter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Cache/RedisCacheAdapter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Email/MailAdapter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Files/FilesAdapter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Files/GridStoreAdapter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Logger/LoggerAdapter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Logger/WinstonLogger' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Logger/WinstonLoggerAdapter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/MessageQueue/EventEmitterMQ' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/PubSub/EventEmitterPubSub' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/PubSub/RedisPubSub' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Push/PushAdapter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Storage/Mongo/MongoCollection' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Storage/Mongo/MongoSchemaCollection' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Storage/Mongo/MongoTransform' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Storage/Postgres/PostgresClient' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Storage/Postgres/PostgresConfigParser' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Adapters/Storage/Postgres/sql/index' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Auth' {
  declare module.exports: any;
}

declare module 'parse-server/lib/batch' {
  declare module.exports: any;
}

declare module 'parse-server/lib/cache' {
  declare module.exports: any;
}

declare module 'parse-server/lib/cli/definitions/parse-live-query-server' {
  declare module.exports: any;
}

declare module 'parse-server/lib/cli/definitions/parse-server' {
  declare module.exports: any;
}

declare module 'parse-server/lib/cli/parse-live-query-server' {
  declare module.exports: any;
}

declare module 'parse-server/lib/cli/parse-server' {
  declare module.exports: any;
}

declare module 'parse-server/lib/cli/utils/commander' {
  declare module.exports: any;
}

declare module 'parse-server/lib/cli/utils/parsers' {
  declare module.exports: any;
}

declare module 'parse-server/lib/cli/utils/runner' {
  declare module.exports: any;
}

declare module 'parse-server/lib/ClientSDK' {
  declare module.exports: any;
}

declare module 'parse-server/lib/cloud-code/httpRequest' {
  declare module.exports: any;
}

declare module 'parse-server/lib/cloud-code/HTTPResponse' {
  declare module.exports: any;
}

declare module 'parse-server/lib/cloud-code/Parse.Cloud' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Config' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Controllers/AdaptableController' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Controllers/AnalyticsController' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Controllers/CacheController' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Controllers/DatabaseController' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Controllers/FilesController' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Controllers/HooksController' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Controllers/LiveQueryController' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Controllers/LoggerController' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Controllers/PushController' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Controllers/SchemaCache' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Controllers/SchemaController' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Controllers/UserController' {
  declare module.exports: any;
}

declare module 'parse-server/lib/cryptoUtils' {
  declare module.exports: any;
}

declare module 'parse-server/lib/defaults' {
  declare module.exports: any;
}

declare module 'parse-server/lib/deprecated' {
  declare module.exports: any;
}

declare module 'parse-server/lib/index' {
  declare module.exports: any;
}

declare module 'parse-server/lib/LiveQuery/Client' {
  declare module.exports: any;
}

declare module 'parse-server/lib/LiveQuery/equalObjects' {
  declare module.exports: any;
}

declare module 'parse-server/lib/LiveQuery/Id' {
  declare module.exports: any;
}

declare module 'parse-server/lib/LiveQuery/ParseCloudCodePublisher' {
  declare module.exports: any;
}

declare module 'parse-server/lib/LiveQuery/ParseLiveQueryServer' {
  declare module.exports: any;
}

declare module 'parse-server/lib/LiveQuery/ParsePubSub' {
  declare module.exports: any;
}

declare module 'parse-server/lib/LiveQuery/ParseWebSocketServer' {
  declare module.exports: any;
}

declare module 'parse-server/lib/LiveQuery/QueryTools' {
  declare module.exports: any;
}

declare module 'parse-server/lib/LiveQuery/RequestSchema' {
  declare module.exports: any;
}

declare module 'parse-server/lib/LiveQuery/SessionTokenCache' {
  declare module.exports: any;
}

declare module 'parse-server/lib/LiveQuery/Subscription' {
  declare module.exports: any;
}

declare module 'parse-server/lib/logger' {
  declare module.exports: any;
}

declare module 'parse-server/lib/middlewares' {
  declare module.exports: any;
}

declare module 'parse-server/lib/ParseMessageQueue' {
  declare module.exports: any;
}

declare module 'parse-server/lib/ParseServer' {
  declare module.exports: any;
}

declare module 'parse-server/lib/ParseServerRESTController' {
  declare module.exports: any;
}

declare module 'parse-server/lib/password' {
  declare module.exports: any;
}

declare module 'parse-server/lib/PromiseRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Push/PushQueue' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Push/PushWorker' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Push/utils' {
  declare module.exports: any;
}

declare module 'parse-server/lib/requiredParameter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/rest' {
  declare module.exports: any;
}

declare module 'parse-server/lib/RestQuery' {
  declare module.exports: any;
}

declare module 'parse-server/lib/RestWrite' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/AnalyticsRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/ClassesRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/CloudCodeRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/FeaturesRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/FilesRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/FunctionsRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/GlobalConfigRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/HooksRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/IAPValidationRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/InstallationsRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/LogsRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/PublicAPIRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/PurgeRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/PushRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/RolesRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/SchemasRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/SessionsRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/Routers/UsersRouter' {
  declare module.exports: any;
}

declare module 'parse-server/lib/StatusHandler' {
  declare module.exports: any;
}

declare module 'parse-server/lib/TestUtils' {
  declare module.exports: any;
}

declare module 'parse-server/lib/triggers' {
  declare module.exports: any;
}

declare module 'parse-server/lib/vendor/mongodbUrl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parse-server/lib/AccountLockout.js' {
  declare module.exports: $Exports<'parse-server/lib/AccountLockout'>;
}
declare module 'parse-server/lib/Adapters/AdapterLoader.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/AdapterLoader'>;
}
declare module 'parse-server/lib/Adapters/Analytics/AnalyticsAdapter.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Analytics/AnalyticsAdapter'>;
}
declare module 'parse-server/lib/Adapters/Auth/AuthAdapter.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/AuthAdapter'>;
}
declare module 'parse-server/lib/Adapters/Auth/facebook.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/facebook'>;
}
declare module 'parse-server/lib/Adapters/Auth/github.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/github'>;
}
declare module 'parse-server/lib/Adapters/Auth/google.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/google'>;
}
declare module 'parse-server/lib/Adapters/Auth/index.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/index'>;
}
declare module 'parse-server/lib/Adapters/Auth/instagram.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/instagram'>;
}
declare module 'parse-server/lib/Adapters/Auth/janraincapture.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/janraincapture'>;
}
declare module 'parse-server/lib/Adapters/Auth/janrainengage.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/janrainengage'>;
}
declare module 'parse-server/lib/Adapters/Auth/linkedin.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/linkedin'>;
}
declare module 'parse-server/lib/Adapters/Auth/meetup.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/meetup'>;
}
declare module 'parse-server/lib/Adapters/Auth/OAuth1Client.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/OAuth1Client'>;
}
declare module 'parse-server/lib/Adapters/Auth/qq.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/qq'>;
}
declare module 'parse-server/lib/Adapters/Auth/spotify.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/spotify'>;
}
declare module 'parse-server/lib/Adapters/Auth/twitter.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/twitter'>;
}
declare module 'parse-server/lib/Adapters/Auth/vkontakte.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/vkontakte'>;
}
declare module 'parse-server/lib/Adapters/Auth/wechat.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/wechat'>;
}
declare module 'parse-server/lib/Adapters/Auth/weibo.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Auth/weibo'>;
}
declare module 'parse-server/lib/Adapters/Cache/CacheAdapter.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Cache/CacheAdapter'>;
}
declare module 'parse-server/lib/Adapters/Cache/InMemoryCache.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Cache/InMemoryCache'>;
}
declare module 'parse-server/lib/Adapters/Cache/InMemoryCacheAdapter.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Cache/InMemoryCacheAdapter'>;
}
declare module 'parse-server/lib/Adapters/Cache/NullCacheAdapter.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Cache/NullCacheAdapter'>;
}
declare module 'parse-server/lib/Adapters/Cache/RedisCacheAdapter.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Cache/RedisCacheAdapter'>;
}
declare module 'parse-server/lib/Adapters/Email/MailAdapter.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Email/MailAdapter'>;
}
declare module 'parse-server/lib/Adapters/Files/FilesAdapter.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Files/FilesAdapter'>;
}
declare module 'parse-server/lib/Adapters/Files/GridStoreAdapter.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Files/GridStoreAdapter'>;
}
declare module 'parse-server/lib/Adapters/Logger/LoggerAdapter.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Logger/LoggerAdapter'>;
}
declare module 'parse-server/lib/Adapters/Logger/WinstonLogger.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Logger/WinstonLogger'>;
}
declare module 'parse-server/lib/Adapters/Logger/WinstonLoggerAdapter.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Logger/WinstonLoggerAdapter'>;
}
declare module 'parse-server/lib/Adapters/MessageQueue/EventEmitterMQ.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/MessageQueue/EventEmitterMQ'>;
}
declare module 'parse-server/lib/Adapters/PubSub/EventEmitterPubSub.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/PubSub/EventEmitterPubSub'>;
}
declare module 'parse-server/lib/Adapters/PubSub/RedisPubSub.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/PubSub/RedisPubSub'>;
}
declare module 'parse-server/lib/Adapters/Push/PushAdapter.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Push/PushAdapter'>;
}
declare module 'parse-server/lib/Adapters/Storage/Mongo/MongoCollection.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Storage/Mongo/MongoCollection'>;
}
declare module 'parse-server/lib/Adapters/Storage/Mongo/MongoSchemaCollection.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Storage/Mongo/MongoSchemaCollection'>;
}
declare module 'parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter'>;
}
declare module 'parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Storage/Mongo/MongoTransform'>;
}
declare module 'parse-server/lib/Adapters/Storage/Postgres/PostgresClient.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Storage/Postgres/PostgresClient'>;
}
declare module 'parse-server/lib/Adapters/Storage/Postgres/PostgresConfigParser.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Storage/Postgres/PostgresConfigParser'>;
}
declare module 'parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter'>;
}
declare module 'parse-server/lib/Adapters/Storage/Postgres/sql/index.js' {
  declare module.exports: $Exports<'parse-server/lib/Adapters/Storage/Postgres/sql/index'>;
}
declare module 'parse-server/lib/Auth.js' {
  declare module.exports: $Exports<'parse-server/lib/Auth'>;
}
declare module 'parse-server/lib/batch.js' {
  declare module.exports: $Exports<'parse-server/lib/batch'>;
}
declare module 'parse-server/lib/cache.js' {
  declare module.exports: $Exports<'parse-server/lib/cache'>;
}
declare module 'parse-server/lib/cli/definitions/parse-live-query-server.js' {
  declare module.exports: $Exports<'parse-server/lib/cli/definitions/parse-live-query-server'>;
}
declare module 'parse-server/lib/cli/definitions/parse-server.js' {
  declare module.exports: $Exports<'parse-server/lib/cli/definitions/parse-server'>;
}
declare module 'parse-server/lib/cli/parse-live-query-server.js' {
  declare module.exports: $Exports<'parse-server/lib/cli/parse-live-query-server'>;
}
declare module 'parse-server/lib/cli/parse-server.js' {
  declare module.exports: $Exports<'parse-server/lib/cli/parse-server'>;
}
declare module 'parse-server/lib/cli/utils/commander.js' {
  declare module.exports: $Exports<'parse-server/lib/cli/utils/commander'>;
}
declare module 'parse-server/lib/cli/utils/parsers.js' {
  declare module.exports: $Exports<'parse-server/lib/cli/utils/parsers'>;
}
declare module 'parse-server/lib/cli/utils/runner.js' {
  declare module.exports: $Exports<'parse-server/lib/cli/utils/runner'>;
}
declare module 'parse-server/lib/ClientSDK.js' {
  declare module.exports: $Exports<'parse-server/lib/ClientSDK'>;
}
declare module 'parse-server/lib/cloud-code/httpRequest.js' {
  declare module.exports: $Exports<'parse-server/lib/cloud-code/httpRequest'>;
}
declare module 'parse-server/lib/cloud-code/HTTPResponse.js' {
  declare module.exports: $Exports<'parse-server/lib/cloud-code/HTTPResponse'>;
}
declare module 'parse-server/lib/cloud-code/Parse.Cloud.js' {
  declare module.exports: $Exports<'parse-server/lib/cloud-code/Parse.Cloud'>;
}
declare module 'parse-server/lib/Config.js' {
  declare module.exports: $Exports<'parse-server/lib/Config'>;
}
declare module 'parse-server/lib/Controllers/AdaptableController.js' {
  declare module.exports: $Exports<'parse-server/lib/Controllers/AdaptableController'>;
}
declare module 'parse-server/lib/Controllers/AnalyticsController.js' {
  declare module.exports: $Exports<'parse-server/lib/Controllers/AnalyticsController'>;
}
declare module 'parse-server/lib/Controllers/CacheController.js' {
  declare module.exports: $Exports<'parse-server/lib/Controllers/CacheController'>;
}
declare module 'parse-server/lib/Controllers/DatabaseController.js' {
  declare module.exports: $Exports<'parse-server/lib/Controllers/DatabaseController'>;
}
declare module 'parse-server/lib/Controllers/FilesController.js' {
  declare module.exports: $Exports<'parse-server/lib/Controllers/FilesController'>;
}
declare module 'parse-server/lib/Controllers/HooksController.js' {
  declare module.exports: $Exports<'parse-server/lib/Controllers/HooksController'>;
}
declare module 'parse-server/lib/Controllers/LiveQueryController.js' {
  declare module.exports: $Exports<'parse-server/lib/Controllers/LiveQueryController'>;
}
declare module 'parse-server/lib/Controllers/LoggerController.js' {
  declare module.exports: $Exports<'parse-server/lib/Controllers/LoggerController'>;
}
declare module 'parse-server/lib/Controllers/PushController.js' {
  declare module.exports: $Exports<'parse-server/lib/Controllers/PushController'>;
}
declare module 'parse-server/lib/Controllers/SchemaCache.js' {
  declare module.exports: $Exports<'parse-server/lib/Controllers/SchemaCache'>;
}
declare module 'parse-server/lib/Controllers/SchemaController.js' {
  declare module.exports: $Exports<'parse-server/lib/Controllers/SchemaController'>;
}
declare module 'parse-server/lib/Controllers/UserController.js' {
  declare module.exports: $Exports<'parse-server/lib/Controllers/UserController'>;
}
declare module 'parse-server/lib/cryptoUtils.js' {
  declare module.exports: $Exports<'parse-server/lib/cryptoUtils'>;
}
declare module 'parse-server/lib/defaults.js' {
  declare module.exports: $Exports<'parse-server/lib/defaults'>;
}
declare module 'parse-server/lib/deprecated.js' {
  declare module.exports: $Exports<'parse-server/lib/deprecated'>;
}
declare module 'parse-server/lib/index.js' {
  declare module.exports: $Exports<'parse-server/lib/index'>;
}
declare module 'parse-server/lib/LiveQuery/Client.js' {
  declare module.exports: $Exports<'parse-server/lib/LiveQuery/Client'>;
}
declare module 'parse-server/lib/LiveQuery/equalObjects.js' {
  declare module.exports: $Exports<'parse-server/lib/LiveQuery/equalObjects'>;
}
declare module 'parse-server/lib/LiveQuery/Id.js' {
  declare module.exports: $Exports<'parse-server/lib/LiveQuery/Id'>;
}
declare module 'parse-server/lib/LiveQuery/ParseCloudCodePublisher.js' {
  declare module.exports: $Exports<'parse-server/lib/LiveQuery/ParseCloudCodePublisher'>;
}
declare module 'parse-server/lib/LiveQuery/ParseLiveQueryServer.js' {
  declare module.exports: $Exports<'parse-server/lib/LiveQuery/ParseLiveQueryServer'>;
}
declare module 'parse-server/lib/LiveQuery/ParsePubSub.js' {
  declare module.exports: $Exports<'parse-server/lib/LiveQuery/ParsePubSub'>;
}
declare module 'parse-server/lib/LiveQuery/ParseWebSocketServer.js' {
  declare module.exports: $Exports<'parse-server/lib/LiveQuery/ParseWebSocketServer'>;
}
declare module 'parse-server/lib/LiveQuery/QueryTools.js' {
  declare module.exports: $Exports<'parse-server/lib/LiveQuery/QueryTools'>;
}
declare module 'parse-server/lib/LiveQuery/RequestSchema.js' {
  declare module.exports: $Exports<'parse-server/lib/LiveQuery/RequestSchema'>;
}
declare module 'parse-server/lib/LiveQuery/SessionTokenCache.js' {
  declare module.exports: $Exports<'parse-server/lib/LiveQuery/SessionTokenCache'>;
}
declare module 'parse-server/lib/LiveQuery/Subscription.js' {
  declare module.exports: $Exports<'parse-server/lib/LiveQuery/Subscription'>;
}
declare module 'parse-server/lib/logger.js' {
  declare module.exports: $Exports<'parse-server/lib/logger'>;
}
declare module 'parse-server/lib/middlewares.js' {
  declare module.exports: $Exports<'parse-server/lib/middlewares'>;
}
declare module 'parse-server/lib/ParseMessageQueue.js' {
  declare module.exports: $Exports<'parse-server/lib/ParseMessageQueue'>;
}
declare module 'parse-server/lib/ParseServer.js' {
  declare module.exports: $Exports<'parse-server/lib/ParseServer'>;
}
declare module 'parse-server/lib/ParseServerRESTController.js' {
  declare module.exports: $Exports<'parse-server/lib/ParseServerRESTController'>;
}
declare module 'parse-server/lib/password.js' {
  declare module.exports: $Exports<'parse-server/lib/password'>;
}
declare module 'parse-server/lib/PromiseRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/PromiseRouter'>;
}
declare module 'parse-server/lib/Push/PushQueue.js' {
  declare module.exports: $Exports<'parse-server/lib/Push/PushQueue'>;
}
declare module 'parse-server/lib/Push/PushWorker.js' {
  declare module.exports: $Exports<'parse-server/lib/Push/PushWorker'>;
}
declare module 'parse-server/lib/Push/utils.js' {
  declare module.exports: $Exports<'parse-server/lib/Push/utils'>;
}
declare module 'parse-server/lib/requiredParameter.js' {
  declare module.exports: $Exports<'parse-server/lib/requiredParameter'>;
}
declare module 'parse-server/lib/rest.js' {
  declare module.exports: $Exports<'parse-server/lib/rest'>;
}
declare module 'parse-server/lib/RestQuery.js' {
  declare module.exports: $Exports<'parse-server/lib/RestQuery'>;
}
declare module 'parse-server/lib/RestWrite.js' {
  declare module.exports: $Exports<'parse-server/lib/RestWrite'>;
}
declare module 'parse-server/lib/Routers/AnalyticsRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/AnalyticsRouter'>;
}
declare module 'parse-server/lib/Routers/ClassesRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/ClassesRouter'>;
}
declare module 'parse-server/lib/Routers/CloudCodeRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/CloudCodeRouter'>;
}
declare module 'parse-server/lib/Routers/FeaturesRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/FeaturesRouter'>;
}
declare module 'parse-server/lib/Routers/FilesRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/FilesRouter'>;
}
declare module 'parse-server/lib/Routers/FunctionsRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/FunctionsRouter'>;
}
declare module 'parse-server/lib/Routers/GlobalConfigRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/GlobalConfigRouter'>;
}
declare module 'parse-server/lib/Routers/HooksRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/HooksRouter'>;
}
declare module 'parse-server/lib/Routers/IAPValidationRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/IAPValidationRouter'>;
}
declare module 'parse-server/lib/Routers/InstallationsRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/InstallationsRouter'>;
}
declare module 'parse-server/lib/Routers/LogsRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/LogsRouter'>;
}
declare module 'parse-server/lib/Routers/PublicAPIRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/PublicAPIRouter'>;
}
declare module 'parse-server/lib/Routers/PurgeRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/PurgeRouter'>;
}
declare module 'parse-server/lib/Routers/PushRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/PushRouter'>;
}
declare module 'parse-server/lib/Routers/RolesRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/RolesRouter'>;
}
declare module 'parse-server/lib/Routers/SchemasRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/SchemasRouter'>;
}
declare module 'parse-server/lib/Routers/SessionsRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/SessionsRouter'>;
}
declare module 'parse-server/lib/Routers/UsersRouter.js' {
  declare module.exports: $Exports<'parse-server/lib/Routers/UsersRouter'>;
}
declare module 'parse-server/lib/StatusHandler.js' {
  declare module.exports: $Exports<'parse-server/lib/StatusHandler'>;
}
declare module 'parse-server/lib/TestUtils.js' {
  declare module.exports: $Exports<'parse-server/lib/TestUtils'>;
}
declare module 'parse-server/lib/triggers.js' {
  declare module.exports: $Exports<'parse-server/lib/triggers'>;
}
declare module 'parse-server/lib/vendor/mongodbUrl.js' {
  declare module.exports: $Exports<'parse-server/lib/vendor/mongodbUrl'>;
}
